### ISSUE TITLE
実装状況＆タスク

### ISSUE THREAD

**Issue by xwasoux** [TeamKuOn/Dionysos#1]
| Task Priority | Device & Function                 | Implement Situation                                            | Library                                                                                                                                                                                    | 
| ------------- | --------------------------------- | -------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | 
| 1             | MCP2515_CAN                       | OS内のポート同士の通信は確認済み<br><br>実機同士の通信は未実装 | pip install python-can<br><br>[hardbyte / python-can](https://github.com/hardbyte/python-can)                                                                                              | 
| 2             | テレメトリ<br>（Soracom Harvest） | 未実装                                                         | + https://users.soracom.io/ja-jp/docs/harvest/raspberry-pi/<br>+ https://qiita.com/yossihard/items/f695addf2508a6f22133<br>+ https://qiita.com/Ichiro_Tsuji/items/1aeb8afd6d6fe4405722<br> | 
| 4             | ドライバーモニタ<br>（GUI）       | 未実装                                                         | tkinter<br>(tkl/tk)                                                                                                                                                                        |

**Comment by xwasoux** [comment]
# CAN 通信

## Task List
+ [ ] CANバスに接続して，Arduino からデータ受信できるか確認する
+ [ ] CAN バスデータはHEX（16進数）に変換しているので，元のデータ型に復元できるようにする
+ [ ] CAN ID によってセンサデータが異なるため，対応付けの実装が必要

**Comment by xwasoux** [comment]
# テレメトリ （SORACOM Harvest）

## Task List
+ [ ] ダミーデータを送信できるかをラズパイとSoracomユーザーログインの両方で確認する
+ [ ] Jsonデータの形式を調べる

**Comment by xwasoux** [comment]
# ドライバーモニタ （GUI）

## Task List
+ [ ] tkinter でCANのデータをラベルで表示できるか確認する
+ [ ] Canvas図形を変数で変えられるかを確認する

**Comment by xwasoux** [comment]
# Option | テレメトリ（サーバー）

## Task List
+ [ ] Plotly/Dash の動作確認（データの更新周期は 10 s）
+ [ ] 外部アクセスが可能かどうかを確認する
